version: '2'
services:
  postgres:
    build: .
    image: postgres:9.6-2.3-2.3
    container_name: posgres_db
    volumes:
      - ./initdb-pgrouting.sh:/docker-entrypoint-initdb.d/001-routing.sh
      - ./sql_dump:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:      
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: glen
      POSTGRES_DB: glen_db
    restart: "no"